### PR TITLE
reverse Box/Hexahedron boundary normal

### PR DESCRIPTION
**Pull request by HaoxuanGuo**
The normals of the geometry should be facing outwards, but the normals generated by calling the boundary method on Box before are facing inwards. Fix this problem now.

### CODE REVIEW

**Comment by juliohm** [comment]
Awesome, that explains why our vizualization was a bit dark. Can you also fix the orientation of the Hexahedron boundary?

**Comment by GuoHaoxuan** [comment]
@juliohm done for Hexahedron

**Comment by juliohm** [comment]
Awesome, thank you for the quick updates. Can we also add some tests so that we don't reintroduce the issue in future adjustments to the code?

**Comment by GuoHaoxuan** [comment]
@juliohm Although we can add a test to generate a ray along the normal with an origin on the surface from each face of the boundary, then the intersection of the ray and the mesh should be nothing. But this is only a mechanical guarantee that the current geometry does not have this problem. We may forget this test when adding new geometry. A better way may be to solve this problem completely by dealing with #137 .

**Comment by juliohm** [comment]
I don't know if I followed the suggestion. Can't we add a test that computes the inner product between all normals and makes sure that the value is never negative? Meaning the normals are pointing outwards?

**Comment by GuoHaoxuan** [comment]
@juliohm I'm afraid not. Because \cdot(-\vec{b})).  The sign of the normal point multiplication has nothing to do with their direction.

**Comment by juliohm** [comment]
Oh sorry, my mistake. If there are no tests that could be written easily here we can go ahead and merge it.

**Comment by GuoHaoxuan** [comment]
@juliohm If we really do a similar test, perhaps we need to use the method of ray judgment. If a point is inside the geometry, then the ray starting from it will have an odd number of intersections with the geometry, otherwise there will be an even number (0 is also an even number). If the normal is facing outward, the point on the surface should be outside the geometry if it moves along the normal, otherwise it should be inside the geometry. Then we can test the number of intersections. Unfortunately, writing such a test is not a simple process. And more importantly, people who add new geometry may forget this test.

**Comment by juliohm** [comment]
Thank you @HaoxuanGuo for explaining the issue. I will go ahead and merge the PR with the improvements. 💯

**Pull request merged**
