### PR TITLE
Circumsphere

### PR DESCRIPTION
**Pull request by stla**
3D sphere passing through four given points

### CODE REVIEW

**Comment by juliohm** [comment]
This PR is mixed up with changes from other PRs.

**Comment by stla** [comment]
Really ? This is a different branch. I thought this was ok like this. But no problem, I will wait for the previous pr.

**Comment by juliohm** [comment]
Click on the "Files changed" tab here and you will find the effective changes introduced by the PR. They contain Torus, CircumSphere, Rotation, ...

**Comment by stla** [comment]
I remade this branch and when running the tests, the `LinearAlgebra` function `norm_sqr` is not found. Why that?

**Comment by juliohm** [comment]
The LinearAlgebra stdlib does not have a norm_sqr function, at least not here on Julia v1.8

**Comment by stla** [comment]
Why I have this function? It is here:

https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/generic.jl#L458

Anyway this is not a good function. I thought it avoided the square root but no, it is defined as `norm(x)^2`.

**Comment by juliohm** [comment]
You are probably using internal functions that are not public with LinearAlgebra.internal_func. That is yet another reason to not use modules as prefixes. A module exports a set of functions as the public api.

**Pull request closed without merging**
