### PR TITLE
Debug GR in CI.yml

### PR DESCRIPTION
**Pull request by mkitti**
Turn on debug statements for GR during Github Actions CI

### CODE REVIEW

**Comment by mkitti** [comment]
https://github.com/jheinen/GR.jl/pull/395 should resolve this as of version v0.57.4. It is just waiting for package registration.

**Comment by juliohm** [comment]
Thank you @mkitti , could you please confirm that this PR can be closed now, and that future PRs will just build correctly on MacOS? I saw that the PR in Plots.jl was already merged.

**Comment by mkitti** [comment]
Let's confirm that CI now passes without the environmental variables.

**Comment by mkitti** [comment]
```julia
  [28b8d3ca] GR v0.57.4
```

The test failures do not look GR related with v0.57.4. Closing.

**Comment by mkitti** [comment]
I also note that the GR tarball which does work uses QT 5:

https://gr-framework.org/downloads/gr-0.57.2-Darwin-x86_64.tar.gz

```
$ tar -tvf gr-latest-Darwin-x86_64.tar.gz
...
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/QtGui -> Versions/Current/QtGui
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Versions/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Versions/Current -> 5
drwxrwxrwx 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Versions/5/
-rwxr-xr-x 501/dialout 6822104 2020-09-03 00:05 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Versions/5/Resources/
-rw-r--r-- 501/dialout    1637 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Versions/5/Resources/QtGui.prl
-rw-r--r-- 501/dialout     636 2020-09-03 00:03 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Versions/5/Resources/Info.plist
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtGui.framework/Resources -> Versions/Current/Resources
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/QtWidgets -> Versions/Current/QtWidgets
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Versions/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Versions/Current -> 5
drwxrwxrwx 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/
-rwxr-xr-x 501/dialout 6492424 2020-09-03 00:06 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/Resources/
-rw-r--r-- 501/dialout     644 2020-09-03 00:05 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/Resources/Info.plist
-rw-r--r-- 501/dialout    1627 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/Resources/QtWidgets.prl
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtWidgets.framework/Resources -> Versions/Current/Resources
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/QtDBus -> Versions/Current/QtDBus
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Versions/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Versions/Current -> 5
drwxrwxrwx 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Versions/5/
-rwxr-xr-x 501/dialout  613236 2020-09-03 00:03 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Versions/5/Resources/
-rw-r--r-- 501/dialout    1444 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Versions/5/Resources/QtDBus.prl
-rw-r--r-- 501/dialout     638 2020-09-03 00:03 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Versions/5/Resources/Info.plist
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtDBus.framework/Resources -> Versions/Current/Resources
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/QtCore -> Versions/Current/QtCore
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Versions/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Versions/Current -> 5
drwxrwxrwx 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Versions/5/
-rwxr-xr-x 501/dialout 6995176 2020-09-03 00:03 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Versions/5/Resources/
-rw-r--r-- 501/dialout     638 2020-09-03 00:02 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Versions/5/Resources/Info.plist
-rw-r--r-- 501/dialout    1498 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Versions/5/Resources/QtCore.prl
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtCore.framework/Resources -> Versions/Current/Resources
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/QtNetwork -> Versions/Current/QtNetwork
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Versions/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Versions/Current -> 5
drwxrwxrwx 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/
-rwxr-xr-x 501/dialout 1659468 2020-09-03 00:04 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources/
-rw-r--r-- 501/dialout    1469 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources/QtNetwork.prl
-rw-r--r-- 501/dialout     644 2020-09-03 00:03 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources/Info.plist
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtNetwork.framework/Resources -> Versions/Current/Resources
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/QtPrintSupport -> Versions/Current/QtPrintSupport
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current -> 5
drwxrwxrwx 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/
-rwxr-xr-x 501/dialout  342476 2020-09-03 00:07 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
drwxr-xr-x 501/dialout       0 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/Resources/
-rw-r--r-- 501/dialout    1636 2020-09-14 03:23 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/Resources/QtPrintSupport.prl
-rw-r--r-- 501/dialout     654 2020-09-03 00:06 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/Resources/Info.plist
lrwxrwxrwx 501/dialout       0 2021-04-20 07:56 gr/Applications/gksqt.app/Contents/Frameworks/QtPrintSupport.framework/Resources -> Versions/Current/Resources
-rw-r--r-- 501/dialout     730 2021-04-20 07:54 gr/Applications/gksqt.app/Contents/Info.plist
-rw-r--r-- 501/dialout       9 2021-04-20 07:54 gr/Applications/gksqt.app/Contents/PkgInfo
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/gksqt.app/Contents/MacOS/
-rwxr-xr-x 501/dialout  599752 2021-04-20 07:54 gr/Applications/gksqt.app/Contents/MacOS/gksqt
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/gksqt.app/Contents/Resources/
-rw-r--r-- 501/dialout       0 2021-04-20 07:54 gr/Applications/gksqt.app/Contents/Resources/empty.lproj
-rw-r--r-- 501/dialout  236190 2021-04-20 07:54 gr/Applications/gksqt.app/Contents/Resources/gksqt.icns
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/GKSTerm.app/
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/_CodeSignature/
-rw-r--r-- 501/dialout    3859 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/_CodeSignature/CodeResources
-rw-r--r-- 501/dialout    1495 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/Info.plist
-rw-r--r-- 501/dialout       8 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/PkgInfo
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/MacOS/
-rwxr-xr-x 501/dialout 1148064 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/MacOS/GKSTerm
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/Resources/
-rw-r--r-- 501/dialout  236912 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/Resources/GKSTerm.icns
drwxr-xr-x 501/dialout       0 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/Resources/English.lproj/
-rw-r--r-- 501/dialout    8089 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/Resources/English.lproj/ExtendSavePanel.nib
-rw-r--r-- 501/dialout     202 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/Resources/English.lproj/InfoPlist.strings
-rw-r--r-- 501/dialout    6600 2021-04-20 07:54 gr/Applications/GKSTerm.app/Contents/Resources/English.lproj/MainMenu.nib
```

**Pull request closed without merging**
